### PR TITLE
Adding socketio

### PR DESCRIPTION
**Pull request by richb-hanover**
Added socket.io to the project.

### CODE REVIEW

**Comment by richb-hanover** [comment]
The <Timebar /> component listens for updates from the API server, sent via socket.io. I hope this is useful as an example.

**Comment by richb-hanover** [comment]
I haven't had a chance to review your websocket/socket.io updates, but they seem more extensive than the simple component I created. I am happy to withdraw this PR, since you've done the heavy lifting.

**Comment by cloudmu** [comment]
@richb-hanover thanks.  Indeed I was wrapping up [server alerts via socket.io](https://github.com/cloudmu/react-redux-starter-kit/commit/78848cd79cc048d792c7d06d02291cd2600a79b3) which is a little closer to my real world socket.io use case. 

I did take a look at your pr. There are some issues you may want to look into later on:
1. npm install fails (your packages.json has errors such as duplicate dependencies and missing comma). 
2. timebar.js calls `setState` in constructor. That's a no-no.  (you will be keep updating unmounted timebar after you navigate to other pages).
3. timebar.js would throw repetitive and excessive exceptions on socket connection errors (e.g. when server is unavailable).

You can observe issues caused by 2&3 by opening the dev console in the browser.

**Comment by richb-hanover** [comment]
Thanks for these comments. I will review my code (some of which made it into my real project) and your code to see how to update my project.

And in case you haven't noticed, create-react-app just got bumped to 0.3.1 [CHANGELOG](https://github.com/facebookincubator/create-react-app/blob/master/CHANGELOG.md) with the addition of Jest testing and many tweaks/bug fixes.

**Pull request closed without merging**
